services:
  api:
    build: .
    command: ./scripts/start-api.sh
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql+psycopg://postgres:secret@postgres:5432/askpolis
    depends_on:
      - postgres
      - redis
      - ollama

  worker:
    build: .
    command: ./scripts/start-worker.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql+psycopg://postgres:secret@postgres:5432/askpolis
    depends_on:
      - postgres
      - redis
      - ollama
      - api

  scheduler:
    build: .
    command: ./scripts/start-scheduler.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - worker

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    command: [ "celery", "--broker=redis://redis:6379/0", "flower", "--port=5555" ]
    ports:
      - "5555:5555"
    depends_on:
      - redis

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: ollama

  redis:
    image: redis:7.4.2-bookworm

  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=askpolis
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
