services:
  redis:
    image: redis:7.4.2-alpine

  api:
    build: .
    command: ./scripts/start-api.sh
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: ./scripts/start-worker.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  scheduler:
    build: .
    command: ./scripts/start-scheduler.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - worker

  flower:
    image: mher/flower:2.0.1
    container_name: flower
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
